title: DataDriven
author: Takreem Akhter
email: akhtertakreem@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog about Big-Data, Machine Learning, Azure services.
  Especially about tools like Apache Spark with PySpark API,
  Python Data-Science libraries, Azure Data Factory, Azure Data Lake,
  Synapse Analytics, cosmosDB and the databricks platform.

# social links
linkedin_username: takreem-akhter # DO NOT include the @ character, or else the build will fail!
github_username:  TakreemAkhter # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
